name: SCSS tests
on: [push, pull_request]
jobs:
  stylelint:
    runs-on: ubuntu-latest
    name: stylelint
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - run: npm install && npm run scss-lint
